- file-format-verification/src/js/index.js
> Update intro content to call out applicability to 2017

- file-format-verification/src/index.html
- file-format-verification/src/js/components/ParseErrors.jsx
> Title and transmittal sheet format update

- README.md
- file-format-verification/Dockerfile
- file-format-verification/package.json
- file-format-verification/src/js/components/ParseErrors.jsx
- file-format-verification/src/js/components/UploadForm.jsx
- file-format-verification/src/sass/components/ParseErrors.scss
Closes #20 
Closes #21 
Closes #22 
Also, shrinks the docker build, expecting `./dist` to be passed in as a volume (similar to hmda-platform-ui).
Running in docker is thus (from the ffvt subdirectory):
```
npm run build
docker build -t ffvt .
docker run -p "3000:80" -v "$(pwd)/dist:/usr/src/app/dist" ffvt
```
> Content updates

- file-format-verification/src/js/actions/index.js
> Make extension case insensitive

- check-digit/src/js/Answer.jsx
- check-digit/src/js/App.jsx
- check-digit/src/js/Form.jsx
Updates the language; a loan id that is entered, not a ULI.
Also, does a small amount of prep to allow for #36. Basically just leaves a few functions and props in place to be used there.
> update langage and functions to match what the app is actually doing

- check-digit/src/js/Answer.jsx
- check-digit/src/js/App.jsx
- check-digit/src/js/Form.jsx
- check-digit/src/js/InputError.jsx
> Do both get and validate for check digit

- check-digit/src/js/Answer.jsx
- check-digit/src/js/App.jsx
- check-digit/src/js/Form.jsx
- moves all the state to the `app.jsx`
- other cleanup and adding comments
> Share state

- check-digit/package.json
- check-digit/src/js/Answer.jsx
- check-digit/src/js/App.jsx
- check-digit/src/js/Form.jsx
- check-digit/src/js/InputError.jsx
- check-digit/src/js/utils/index.js
- check-digit/yarn.lock
This has quite a few updates, mostly cleaning things up a bit.
But, more importantly this should be ready to go live using the public endpoint.
Also closes #28
> Ready to go live

- file-format-verification/package-lock.json
- file-format-verification/package.json
Closes #40 (had to update node-sass to build)
> update packages to add new NA parsing checks

- check-digit/src/js/App.jsx
- check-digit/src/js/Form.jsx
Closes #46 
More issues have been created to handle other parts of #46. This PR disables the submit button until we have valid input.
> Disable button

- check-digit/src/js/Form.jsx
- check-digit/src/sass/_hmda.scss
Closes #45 
There's a weird double border-bottom caused by `normalize.css`. We can remove it but I imagine it's needed in some cases. Let me know what you think.
> add abbr to explain ULI and LEI

- check-digit/src/js/Form.jsx
- check-digit/src/js/utils/index.js
Closes #58 
Also has a [quick update](https://github.com/cfpb/hmda-platform-tools/pull/60/commits/35ee010912921d8844804c306aa68c8e097c44df) to change the min ULI length to 23.
> Uswds error

- check-digit/src/js/LoadingIcon.jsx
- check-digit/yarn.lock
Quick fix for the loading icon.
_I've already updated `gh-pages`._
> fix loading icon

- check-digit/src/js/AppIntro.jsx
> update intro text for clearance

- package.json
- rate-spread/src/js/AppIntro.jsx
- rate-spread/src/js/Form.jsx
- rate-spread/src/requirements.html
- rate-spread/src/sass/_Form.scss
- rate-spread/src/sass/_hmda.scss
Also, adds data requirements page.
Depends on #71
Closes #62 
Closes #63
> Cleared language

- rate-spread/src/js/Form.jsx
- rate-spread/src/sass/_Form.scss
Closes #68 
Validation implemented for 3 input forms and submit button disabled based on validation state.
> Validation

- rate-spread/src/js/AppIntro.jsx
> link to tables

- check-digit/src/js/utils/index.js
> Fix for LEI/loan id min characters

- rate-spread/src/js/Form.jsx
Prevents an issue when submitting too early with an accidental return could cause malformed requests
> Force validation on submit to display errors based on state

- file-format-verification/src/js/actions/index.js
- file-format-verification/src/js/components/Pagination.jsx
- file-format-verification/src/js/components/ParseErrors.jsx
- file-format-verification/src/js/constants/index.js
- file-format-verification/src/js/containers/Pagination.jsx
- file-format-verification/src/js/containers/ParseErrors.jsx
- file-format-verification/src/js/notes.txt
- file-format-verification/src/js/reducers/index.js
- file-format-verification/src/sass/app.scss
- file-format-verification/src/sass/components/_Pagination.scss
- rate-spread/src/js/Form.jsx
> Ffvt pagination

- rate-spread/src/js/Form.jsx
> Display more accurate text for variable amortization type

- file-format-verification/src/js/index.js
- webpack.config.js
> Conditional ffvt logs

- rate-spread/src/js/AppIntro.jsx
> Adds survey table link to appintro

- rate-spread/src/js/App.jsx
> update content for APOR tables

- src/check-digit/CSVUpload.jsx
> fix typo ... rate spread should be check digit

- env.sh
- src/index.js
- src/sass/uswds-customer-vars.scss
- src/shared-components/AppHeader.jsx
With https://github.com/cfpb/hmda-platform-ui/pull/1069
> Update envvar for consistency and add filing link

- src/App.jsx
- src/Home.jsx
- src/app.scss
- src/rate-spread/AppIntro.jsx
- src/rate-spread/Methodology.jsx
- src/rate-spread/Methodology.scss
- src/rate-spread/Requirements.jsx
> Methodology

- src/rate-spread/Form.jsx
> clear response if inputs change

- package.json
- yarn.lock
Update to go with cfpb/hmda-ui-modules#5.
> bump for active links

- src/file-format-verification/components/Pagination.jsx
> Base pagination render check on page count

- src/Home.jsx
Helps to close https://github.com/cfpb/hmda-homepage/issues/34
> Capitalize tools

- nginx/nginx.conf
See https://github.com/cfpb/hmda-pub-ui/issues/203
> fix refresh when at /tools/something-else

- Jenkinsfile
Node name should correspond to `podTemplate.label`.
> Jenkins Node Name Fix

- src/check-digit/index.jsx
- src/file-format-verification/actions/index.js
> update use of / to account for ambassador config

- Jenkinsfile
See: https://github.com/cfpb/hmda-pub-ui/pull/210
> Push Images to Internal Repo and Tag Images on Git Tags

- .prettierrc
- src/rate-spread/CSVUpload.jsx
- src/rate-spread/Form.jsx
Let's talk about this at standup and make sure this is right, that we won't be migrating these endpoints in time for the release.
Closes #182
> WIP - Rate spread api

- src/Header.jsx
Depends on cfpb/hmda-platform-ui#1189
> update link to point to 2018 UI

- src/Header.css
> Fix class typo

- src/lar-formatting/AppIntro.jsx
> update larft link and text

- src/rate-spread/index.jsx
> add APOR notice and date older notice

- src/file-format-verification/actions/index.js
- src/file-format-verification/components/FilingPeriodSelector.jsx
- src/file-format-verification/components/ParseErrors.css
- src/file-format-verification/components/ParseErrors.jsx
- src/file-format-verification/reducers/index.js
Closes #225 
Mirrors changes made to the `hmda-frontend` repo in https://github.com/cfpb/hmda-frontend/pull/23
> Update FFVT API return format
